name: A workflow to build pgBouncer packages
on: push
jobs:
  build:
    name: Build pgBouncer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./debian-build
        with:
          PGBOUNCER_VERSION: "1.14.0"
      - uses: actions/upload-artifact@v2
        with:
          name: pgbouncer-debian-build
          path: /home/runner/work/pgbouncer-builds/pgbouncer-builds/output
      - uses: actions/download-artifact@v2
        with:
          name: pgbouncer-debian-build 
          path: ~/build
  install:
    needs: build
    name: Install pgBouncer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./debian-install
        with:
          PGBOUNCER_VERSION: "1.14.0"
